name: Python CI/CD

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint code
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=hello_world tests/ --cov-fail-under=50
        env:
          PYTHONPATH: .

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./.pytest_cache/

  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run hello_world.py and save output to HTML
        run: |
          python hello_world.py > output.html
          echo "<html><body><pre>" >> output.html
          python hello_world.py >> output.html
          echo "Beta Testing is in the way" >> output.html
          echo "</pre></body></html>" >> output.html

      - name: Commit and push output.html
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output.html
          git commit -m "Add output.html file"
          git push

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: output.html

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Deploy output.html
        run: |
          # Simulate deployment (replace with actual deployment commands)
          echo "Deploying output.html to production..."
          cat output.html
